version: 1
formatters:
    simple:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout
    file:
        class: logging.FileHandler
        level: DEBUG
        formatter: simple
        filename: lgbm_logs.log
        mode: a
        encoding: utf8
    cat_file:
        class: logging.FileHandler
        level: DEBUG
        formatter: simple
        filename: cat_logs.log
        mode: a
        encoding: utf8
    etc_file:
        class: logging.FileHandler
        level: DEBUG
        formatter: simple
        filename: etc_logs.log
        mode: a
        encoding: utf8
    lgbm_lb_file:
        class: logging.FileHandler
        level: DEBUG
        formatter: simple
        filename: lgbm_lb_logs.log
        mode: a
        encoding: utf8
loggers:
    LGBM:
        level: DEBUG
        handlers: [file, console]
    LGBM_lb:
        level: DEBUG
        handlers: [lgbm_lb_file, console]
    ETC:
        level: DEBUG
        handlers: [etc_file, console]
    CatBoost:
        level: DEBUG
        handlers: [cat_file, console]
    root:
        level: DEBUG
        handlers: [console]